name: Check Cargo.toml version
description: Check Cargo.toml version for consistency with the current git ref

runs:
  using: composite
  steps:
    - run: |
        crate_version=$(cargo read-manifest | grep -Eo '"version":"[0-9\.]+"' | grep -Eo '[0-9.]+')
        test "v$crate_version" = "$GITHUB_REF_NAME"
      shell: bash
